name: Java Maven Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout le code
      uses: actions/checkout@v3

    - name: Installer Java (JDK 17)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compiler le projet avec Maven
      run: mvn compile

    - name: Exécuter les tests JUnit
      run: mvn test
